### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by taumuon** [mellinoe/vk#16]
Hi, I noticed something when trying out the tutorial code.

When rendering the triangle example, the color seems to be missing from the third vertex:
<img width="701" alt="trianglecs" src="https://user-images.githubusercontent.com/1922902/39961371-92e9e40a-562c-11e8-95b3-00dd32c38e17.png">

I build the C++ version of the Sascha Willems example and the triangle is rendered as expected:
<img width="641" alt="trianglecpp" src="https://user-images.githubusercontent.com/1922902/39961378-a977eece-562c-11e8-917d-fc5c24b5516a.png">

I can get your vk triangle example to render the same as the c++ by changing the size of the vertexBufferSize to 78 (instead of the calculated 72), but I can't see why this works, or why it should be necessary.
I don't suppose you know what's happening?
Thanks,
gary

**Comment by mellinoe** [comment]
That's pretty odd. I don't see anything wrong on my end without changing anything. I'm running on Nvidia here. The vertex data should only need 72 bytes. Each vertex has 6 floats for a total of 24 bytes each, and there's 3 of them.

That is odd that Sascha's works -- there must be some subtle difference somewhere.

**Comment by FacticiusVir** [comment]
Is this a vertex packing issue? GLSL will typically pad (vec3, vec3) with an extra float after each to keep to 16-byte boundaries.

**Comment by mellinoe** [comment]
Vertex attributes aren't padded out, that should only apply to things like uniform or storage buffers.

**Comment by taumuon** [comment]
It is strange as it seems like only the last color isn't being copied across. I tried it with 4 triangle points and saw the same behavior - the last color is missing, but by increasing the vertexBufferSize by 4 (bytes), the last point is rendered in the correct color.

I can't see any reason for this, the code looks identical between the c++ and c#. I changed the FixedArray3<Vertex> to a flat array of 18 floats, and copy the data manually instead of Unsafe.CopyBlock, and all are showing the same behaviour.
It feels like it must be something in the marshalling, but I don't know why that would be only on my machine ?

thanks for looking into it, any more help is appreciated!

**Comment by mellinoe** [comment]
That's leaving me stumped. Any chance you are running the sample in 32-bit mode or something unusual like that? If I was able to repro the issue, my next step would be taking a look at a capture under [RenderDoc](https://renderdoc.org/). It's not terribly difficult to use, and incredibly helpful for diagnosing issues like this.

**Comment by taumuon** [comment]
Hi, it's definitely 64 bit. I can see in RenderDoc, in the VS Input pane, that the color of the last index is missing..
Thanks, gary

**Comment by taumuon** [comment]
Hi, after spending ages debugging both examples in parallel, I found the difference!

In Sascha's code it has:
vertexInputAttributs[0].format = VK_FORMAT_R32G32B32_SFLOAT;
vertexInputAttributs[1].format = VK_FORMAT_R32G32B32_SFLOAT;

whereas the triangle example has:
vertexInputAttributs[0].format = VkFormat.R32g32b32a32Sfloat;
vertexInputAttributs[1].format = VkFormat.R32g32b32a32Sfloat;

changing this to match Sascha's:
vertexInputAttributs[0].format = VkFormat.R32g32b32Sfloat;
vertexInputAttributs[1].format = VkFormat.R32g32b32Sfloat;

it all works as expected!

Thanks,
gary

**Comment by taumuon** [comment]
though I'm surprised in the symptoms of specifying the wrong format - I've no idea why that would result in it missing a single point off the end of the vertex buffer, I'd have thought that something more catastrophic would happen...

**Comment by mellinoe** [comment]
Ah, thanks for spending the time to debug through this! I'm surprised that I don't see any problems on my Nvidia drivers. Very strange. I'll put up your fix momentarily.

**Comment by mellinoe** [comment]
Should be fixed now. Let me know if you come across any other issues in the other samples.
