### ISSUE TITLE
VkPhysicalDeviceMemoryProperties does not have a function to iterate.

### ISSUE THREAD

**Issue by SamHSmith** [mellinoe/vk#25]
The struct VkPhysicalDeviceMemoryProperties does not have any method of actually iterating over supported memory.

[Here is a link to the generated code.](https://github.com/mellinoe/vk/blob/bcf5e4eb0d28419773374f7d70ad1296f4456424/src/vk/Generated/Structures.gen.cs)

**Comment by mellinoe** [comment]
Yes, the generator creates a completely raw structure with no frills on it. You will want to use something like [this helper](https://github.com/mellinoe/veldrid/blob/1ebe8c67a8e43c7ebe9ccb1174c8beb5221a5498/src/Veldrid/Vk/VulkanUtil.cs#L288-L291) to make it more user-friendly.
