### ISSUE TITLE
Update to vulkan 1.2 SDK

### ISSUE THREAD

**Issue by FaberSanZ** [mellinoe/vk#26]
Hi,

First of all, thank you very much for the librarie.
Any plans to update to newest 1.2 release?

**Comment by mellinoe** [comment]
I would like to update, but it's very unlikely that I will have time for this anytime soon. And as I've said elsewhere, the next update to this library will be a complete overhaul based on how I've been using it. Keep in mind that you are able to manually load extensions and their function pointers today, but it is considerably more work.

**Comment by FaberSanZ** [comment]
Great, I'm using your library and it's the best.

I'm going to buy an RTX in the future and would love to try Vulkan. 

I hope you'll be encouraged to update soon.
